apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: dbz-kafka-connect-cluster
  name: connector-oracle11g
spec:
  class: "io.debezium.connector.oracle.OracleConnector"
  ########################################################################################
  # The Oracle connector always uses a single task and therefore does not use this value #
  # tasksMax: 1                                                                          #
  ########################################################################################
  config:
    database.history.kafka.bootstrap.servers: "dbz-cluster-kafka-bootstrap:9092"
    database.history.kafka.topic: "schema-changes.oracle11g"
    database.hostname: "oracle11g"
    database.port: 1521
    database.user: "dbzuser"
    database.password: "dbz"
    database.dbname: "XE"
    database.server.name: "oracle11g"
    schema.include.list: "DBZUSER"
    table.include.list: "DBZUSER.CUSTOMERS"

